ARG JAVA_VERSION
FROM ${JAVA_VERSION}

ARG JAR_FILE
ARG WORKINGDIR

COPY ./${JAR_FILE} /usr/build/${JAR_FILE}
ENTRYPOINT cp /usr/build/${JAR_FILE} ${WORKINGDIR}/${JAR_FILE} && java -jar ${WORKINGDIR}/${JAR_FILE}
